name: Lint
run-name: ${{ github.workflow }}-${{ github.actor }}-${{ github.event.head_commit.message}}
on:
  push:
    branches:
      - main
      - ci-cd
  pull_request:
    branches:
      - main
jobs:
  run-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Debug Directory Structure
        run: |
          ls -R

      - name: Install Dependencies
        run: yarn

      - name: Run Linter
        run: yarn lint
